server:
  port: 8023
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.163.com
    port: 465
    username: 17302598362@163.com
    password: NLWIZOCAPFAOMQHP
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtps
logging:
  level:
    com.nowcoder.community: debug

mybatis:
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

